USE RetailSalesDB;

-- PROCEDURE 1
-- Question:
-- Display all orders placed by a specific customer.

DELIMITER $$

CREATE PROCEDURE GetCustomerOrders(IN CustID INT)
BEGIN

SELECT
    o.OrderID,
    p.ProductName,
    o.Quantity,
    o.OrderDate,
    (o.Quantity * p.Price) AS Amount
FROM Orders o
JOIN Products p
ON o.ProductID = p.ProductID
WHERE o.CustomerID = CustID;

END$$

DELIMITER ;

-- Example
CALL GetCustomerOrders(10);


-- PROCEDURE 2
-- Question:
-- Calculate total revenue generated by a specific category.

DELIMITER $$

CREATE PROCEDURE GetCategoryRevenue(IN Cat VARCHAR(50))
BEGIN

SELECT
    p.Category,
    SUM(o.Quantity * p.Price) AS Revenue
FROM Products p
JOIN Orders o
ON p.ProductID = o.ProductID
WHERE p.Category = Cat
GROUP BY p.Category;

END$$

DELIMITER ;

-- Example
CALL GetCategoryRevenue('Electronics');


-- PROCEDURE 3
-- Question:
-- Display all orders of a specific order status.

DELIMITER $$

CREATE PROCEDURE GetOrdersByStatus(IN StatusName VARCHAR(20))
BEGIN

SELECT *
FROM Orders
WHERE OrderStatus = StatusName;

END$$

DELIMITER ;

-- Example
CALL GetOrdersByStatus('Delivered');